steps:
  # Build an image
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "--tag=eu.gcr.io/$PROJECT_ID/cloudbuilder-sast", "."]
  # Test the image
  - name: "eu.gcr.io/${PROJECT_ID}/cloudbuilder-sast"
    args: ["--help"]
  # Push the image.
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'eu.gcr.io/$PROJECT_ID/cloudbuilder-sast']
  # Only keep the 10 most recent images
  - name: 'gcr.io/cloud-builders/gcloud-slim'
    entrypoint: 'bash'
    args:
    - '-c'
    - |
      set -eou pipefail
      for digest in $(gcloud container images list-tags eu.gcr.io/$PROJECT_ID/cloudbuilder-sast --limit=99999 --sort-by=TIMESTAMP --format='get(digest)' | head -n-10); do
        gcloud container images delete -q --force-delete-tags "eu.gcr.io/$PROJECT_ID/cloudbuilder-sast@$${digest}"
      done
